### ISSUE TITLE
Source Folder Permission denied

### ISSUE THREAD

**Issue by IoscaA** [supermavster/docker-laravel-8#1] opened 2020-11-05 16:39 UTC
Hello my friend,
Today I wanted to put my laravel project online with docker. I followed your guide, but after putting my project in the "source" folder and running the command "docker-compose run --rm composer install" this error appeared:
"[ErrorException]
   file_put_contents (/var/www/html/vendor/composer/installed.json): failed to open stream: Permission denied "

Could you help me with this problem? I'm nooby with Docker and Laravel. Thanks for what you do! 👍 

PS. My server run: Ubuntu 20.04.1 Focal Fossa

**Comment by supermavster** [comment] 2020-11-06 01:07
Hello @IoscaA, I think that the problem is that your `composer.json` has only permissions of you user, for give you a solution i modify a one file that assign to any files in the project to the profile `laravel` with group `laravel` to execute in the build of Docker.

In short words:
To the file `composer.json` I assign the permissions and group general (in this case laravel) using Docker.

```sh
# Set Profile to All Files
RUN chown -R laravel:laravel /var/www/html
```

That is show in the next Pull Request: #2 


IF that solution not work, only tell me 😉.

**Comment by IoscaA** [comment] 2020-11-06 10:06
Hello @supermavster, I updated the Dockerfile, and It works perfectly! :D 

Thanks so much from Italy 👍

**Closed as completed** 2020-11-06 20:37 UTC
Labels: bug
